# Add repos
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/core"
tap "little-angry-clouds/homebrew-my-brews"
tap "nektos/tap"

# packages
brew "nektos/tap/act"
brew "awscli"
brew "fzf"
brew "gitlab-runner"
brew "go"
brew "hadolint"
brew "little-angry-clouds/homebrew-my-brews/helmenv"
brew "htop"
brew "infracost"
brew "istioctl"
brew "jq"
brew "kind"
brew "kube-linter"
brew "kubernetes-cli"
brew "krew"
brew "pre-commit"
brew "tfenv"
brew "tflint"
brew "tmux"
brew "terraform-ls"
brew "terraform-docs"
brew "tree"
brew "shellcheck"
brew "stern"
brew "vim"
brew "watch"
brew "wget"
brew "yq"


if OS.mac?

  tap "homebrew/cask"
  tap "homebrew/cask-fonts"

  brew "bash"
  brew "bash-completion@2"
  brew "coreutils"
  brew "findutils"
  brew "git"
  brew "gnupg"
  brew "gsed"

  # apps
  cask "docker"
  cask "drawio"
  cask "evernote"
  cask "firefox"
  cask "font-hack-nerd-font"
  cask "google-cloud-sdk"
  cask "iterm2"
  cask "maccy"
  cask "rectangle"
  cask "spotify"
  cask "visual-studio-code"

end
